config/routes.rb
Rails.application.routes.draw do

  # StaticPages
  root 'static_pages#top'

  # Rooms
  get  '/new',      to: 'rooms#new',    as: 'new_room'
  post '/new',      to: 'rooms#create', as: 'create_room'
  get  '/:room_id', to: 'rooms#show',   as: 'room'
  # get   '/:room_id/room_edit', to: 'rooms#room_edit',   as: 'room_edit'   # あとで作る
  # patch '/:room_id/room_edit', to: 'rooms#room_update', as: 'room_update' # あとで作る
  get   '/:room_id/user_edit', to: 'rooms#user_edit',   as: 'user_edit'
  patch '/:room_id/user_edit', to: 'rooms#user_update', as: 'user_update'

  # devise
  devise_for :users, path: ':room_id', path_names: {
    sign_in: 'login', sign_out: 'logout', sign_up: 'new'
  }

  # Posts
  post '/:room_id/create', to: 'posts#create', as: 'create_post'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :room
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
end

app/models/room.rb
class Room < ApplicationRecord
  # association
  has_many :users, dependent: :destroy
  has_many :posts, dependent: :destroy

  # validation
  VALID_CODE_REGEX = /\A[\w-]+\z/ # a-z A-Z 0-9 _ -
  validates :code,
    presence: true,
    uniqueness: true,
    length: { in: 8..255 },
    format: { with: VALID_CODE_REGEX}
  validates :name,
    presence: true,
    length: { maximum: 255 }

  # クラスメソッド

  # a-zA-Z0-9_-から成る8文字の文字列を返す
  def self.random_code
    SecureRandom.urlsafe_base64(nil, false)[0..7]
  end


  # インスタンスメソッド

  # codeのみについて有効かどうかをbooleanで返す
  def has_valid_code?
    self.errors.clear
    self.valid?
    result = self.errors.messages[:code].count.zero?
    self.errors.clear
    return result
  end

end

app/models/user.rb
class User < ApplicationRecord
  # association
  belongs_to :room
  has_many :posts
  has_one_attached :icon

  # validation
  validates :room_id, presence: true
  VALID_NAME_REGEX = /\A[\w-]+\z/ # a-z A-Z 0-9 _ -
  validates :name,
    presence: true,
    uniqueness: { case_sensitive: false },
    length: { maximum: 255 },
    format: { with: VALID_NAME_REGEX}
  validates :display_name, length: { maximum: 255 }

  # Devise
  devise :database_authenticatable, :registerable,
    :rememberable, :validatable

  def email_required?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # devise, ユーザ項目にアイコンである:iconを含められるようにする
  # ※ usernameはすでにログインに必須の要素と扱っているため、追加は不要。
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:icon])
    devise_parameter_sanitizer.permit(:edit, keys: [:icon])
  end

  # サインアップ後にルームトップを表示
  def after_sign_up_path_for(resource)
    room_path(params[:room_id])
  end

  # ログイン後にルームトップを表示
  def after_sign_in_path_for(resource)
    room_path(params[:room_id])
  end

  # ログアウト後にサイトトップを表示
  def after_sign_out_path_for(resource)
    root_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @room = Room.find_by(code: params[:room_id])
    @post = Post.new(user_params)
    if @post.save
      # 保存に成功した場合の処理
      #flash[:success] = "ポスト成功" # うるさいので抑制
      respond_to do |format|
        format.html { redirect_to room_path(@room.code) }
        format.js
      end
    else
      # 保存に失敗した場合の処理
      flash.now[:danger] = "ポスト失敗"
      render 'rooms#show'
    end
  end

  private

  def user_params
    params.require(:post).permit(:room_id, :user_id, :content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :check_signed_in, only: [:show, :user_update]
  before_action :check_correct_room, only: [:show, :user_update]

  def new
    @room = Room.new
    # ルームID（.code）の初期値を自動生成する
    if @room.code.nil?
      until @room.has_valid_code?
        @room.code = Room.random_code
      end
    end
  end

  def create
    @room = Room.new(room_params)
    if @room.save # 保存に成功した場合
      flash[:success] = "ルームが作成されました。"
      flash[:info] = "ユーザ登録を行ってください。"
      redirect_to new_user_registration_path(@room.code) # ユーザ新規登録へ移動
    else # 保存に失敗した場合
      flash.now[:danger] = "ルームの作成に失敗しました。"
      render 'new'
    end
  end

  def show
    @post = Post.new
    @room = Room.find_by(code: params[:room_id])
    # ルームが見つからない場合にはトップページへ移動
    if @room.nil?
      flash[:warning] = "ルーム #{params[:room_id]} が見つかりません。"
      redirect_to root_path
    end
  end

  def user_edit
    @user = User.find(current_user.id)
  end

  def user_update
    @user = User.find(current_user.id)
    @room = Room.find_by(code: params[:room_id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to room_path(params[:room_id])
    else
      flash.now[:danger] = "Failed to update user info"
      render 'devise/registrations/edit'
    end

  end


  private

  def room_params
    params.require(:room).permit(:code, :name)
  end

  def user_params
    params.require(:user).permit(:name, :display_name, :icon)
  end

  # before_actions

  def check_signed_in
    room = Room.find_by(code: params[:room_id])
    unless user_signed_in?
      flash[:danger] = "ログインしてください。"
      redirect_to new_user_session_path(room.code)
    end
  end

  def check_correct_room
    unless current_user.room.code == params[:room_id]
      flash[:danger] = "ログイン中のアカウントではこのルームにアクセスできません。
                        一度ログアウトしてからログインし直してください。"
      redirect_to root_path
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def top
    # 開発環境の場合のみ、デバッグ表示のためにルーム一覧を取得しておく
    if Rails.env.development?
      @rooms = Room.all
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def build_title(page_title = '')
    base_title = "すてチャ(仮)"
    if page_title.empty?
      base_title
    else
      page_title + " - " + base_title
    end
  end

  def current_room_id
    if params[:room_id]
      current_room = Room.find_by(code: params[:room_id])
      current_room.id
    else
      return nil
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_flash.html.slim
- if flash.any?
  #flash_message
    - flash.each do |message_type, message|
      - message_type = "info" if message_type == "notice"
      - message_type = "warning" if message_type == "alert"
      - alert_class = "alert alert-" + message_type
      = content_tag :div, class: alert_class do
        = content_tag :div, message, class: "container"

app/views/layouts/_header.html.slim
header
  nav.navbar.navbar-expand-sm.navbar-dark.bg-primary.fixed-top
    .container
      = link_to "すてチャ(仮)", root_path, class: "navbar-brand"
      button.navbar-toggler[type="button" data-toggle="collapse" data-target="#topHambergerMenu" aria-controls="topHambergerMenu" aria-expanded="false" aria-label="Toggle navigation"]
        span.navbar-toggler-icon
      #topHambergerMenu.collapse.navbar-collapse.justify-content-end
        .navbar-nav.text-right.text-sm-left
          / 以下のメニュー項目は仮のもの。
          - if user_signed_in? # すでにログイン済みの状態
            = link_to "ログイン済みのルームへ移動",
              room_path(current_user.room.code), class: "nav-item nav-link"
            = link_to "ユーザ情報の変更",
              user_edit_path(current_user.room.code), class: "nav-item nav-link"
            = link_to "ログアウト",
              destroy_user_session_path(current_user.room.code),
              method: :delete, class: "nav-item nav-link"
          - elsif params[:room_id] # ルームトップなどに居るが未ログインの状態
            = link_to "ログイン",
              new_user_session_path(params[:room_id]),
              class: "nav-item nav-link"

app/views/layouts/_meta.html.slim
meta[http-equiv="X-UA-Compatible" content="IE=edge"]
meta[charset="utf-8"]
meta[name="description" content=""]
meta[name="author" content=""]
meta[name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"]

app/views/layouts/application.html.slim
doctype html
html
  head
    = render 'layouts/meta'
    title
      = build_title(yield(:page_title))
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    = render 'layouts/header'
    main
      = render 'layouts/flash'
      .container
        = yield

app/views/posts/_show.html.slim
- # 既存ポスト表示欄
.my-3
  h2
    | Post List
  ul
    - room.posts.each do |post|
      li
        - author = User.find(post.user_id)
        = author.display_name.nil? ? author.name : author.display_name
        | :&nbsp;
        = post.content
        |  (
        = post.created_at
        | )

app/views/posts/create.js.erb
$("form#new_post")[0].reset();
$("#posts_list").html("<%= escape_javascript(render 'posts/show', room: @room) %>");

app/views/rooms/_posts.html.erb
<%# 既存ポスト表示欄 %>
<div class="my-3">
  <h2>Post List</h2>
  <ul>
  <% @room.posts.each do |post| %>
    <li><%= User.find(post.user_id).name %>: <%= post.content %> (<%= post.created_at %>)</li>
  <% end %>
  </ul>
</div>

app/views/rooms/new.html.slim
- provide :page_title, "ルーム作成"
h1.my-2
  | ルーム作成
= form_with(model: @room, url: create_room_path, local: true) do |f|
  = render 'shared/error_messages', object: f.object
  .my-4
    = f.label :code do
      div
        |  ルームIDを決めてください
        ul.small.my-0.pl-4
          li
            | IDはルームのURLの一部になります
        ul.my-0.pl-4
          li
            = ENV['BASE_URL']
            | /[ルームID]
      li
        | 長さは8〜255文字です
      li
        | 入力されている初期値から変更できます
      li
        | アルファベット、数字、ハイフン( - )、アンダースコア( _ )が使えます
    = f.text_field :code, class: 'form-control ml-4 w-75'
  .my-4
    = f.label :name do
      |  ルームの名前を決めてください
      ul.small.my-0.pl-4
        li
          | ルーム画面で参加者に表示されます
        li
          | 長さは1〜255文字です
    = f.text_field :name, class: 'form-control ml-4 w-75'
  .my-4.text-center
    = f.submit "ルーム作成", class: "btn btn-primary"

app/views/rooms/show.html.slim
/ 新規ポスト入力欄
= form_with(model: @post, url: create_post_path, id: 'new_post') do |f|
  = f.hidden_field :room_id, value: current_room_id
  = f.hidden_field :user_id, value: current_user.id
  = render 'shared/error_messages', object: f.object
  .my-4
    = f.label :content
    = f.text_field :content, class: 'form-control w-75',
        autofocus: true, autocomplete: "off"
    = f.submit "投稿", class: "btn btn-primary"

/ 既存ポスト表示欄
#posts_list
  = render 'posts/show', room: @room

/ show only in development environment
- if Rails.env.development?
  = render 'shared/debug_info'

app/views/rooms/user_edit.html.slim
- provide :page_title, "ユーザ編集"
h1.my-2
  | ユーザ編集
= form_with(model: @user, url: user_update_path(params[:room_id]), local: true) do |f|
  = render 'shared/error_messages', object: f.object
  .field.my-4
    = f.label :name
    br
    = f.text_field :name, autofocus: true, autocomplete: "username"
  .field.my-4
    = f.label :display_name
    br
    = f.text_field :display_name
  .field.my-4
    = f.label :icon
    div
      p
        | 現在のアイコン
      p
        - icon_image = \
            current_user.icon.attached? ? current_user.icon : "/nobody.png"
        = image_tag icon_image, size: "64", style: 'border-radius: 100%'
    div
      = f.file_field :icon
  .actions
    = f.submit "更新", class: "btn btn-primary"

app/views/shared/_debug_info.html.slim
= content_tag :div, class: "bg-info" do
  h2
    | Debug Info:
  .m-3
    h2
      | Params
    = debug(params)
  .m-3
    h2
      | Room
    ul
      li
        | id:
        = @room.id
      li
        | code:
        = @room.code
      li
        | name:
        = @room.name
  .m-3
    h2
      | Current Session
    ul
      li
        | Signed in:
        = user_signed_in?
      - if user_signed_in?
        li
          | User ID:
          = current_user.id
        li
          | User Name:
          = current_user.name
        li
          | User Image:
          - icon_image = \
              current_user.icon.attached? ? current_user.icon : "/nobody.png"
          = image_tag icon_image, size: "64", style: 'border-radius: 100%'
        li
          | Session:
          = user_session
  .m-3
    h2
      | User List
    ul
      - @room.users.each do |user|
        li
          = user.id
          | :
          = user.name

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      = object.errors.count
      | 個のエラーがあります 
      ul.small.my-0.pl-4
        - object.errors.full_messages.each do |msg|
          li
            = msg

app/views/static_pages/_room_index.html.slim
= content_tag :div, class: "bg-info" do
  h2
    | Debug Info:
  .m-3
    h2
      | Room Index:
    ul
      - @rooms.each do |room|
        li
          = link_to "#{room.id}: #{room.code}", room_path(room.code)

app/views/static_pages/top.html.slim
- provide :page_title, ""
.text-center.m-4
  = link_to "ルーム作成", new_room_path, class: "btn btn-outline-primary"

/ show only in development environment
- if Rails.env.development?
  = render 'room_index'